CREATE TABLE ITEMS (ID INT PRIMARY KEY, ITEM_NAME VARCHAR(25));
INSERT INTO ITEMS (ID,ITEM_NAME) VALUES (1,'Honey');
INSERT INTO ITEMS (ID,ITEM_NAME) VALUES (2,'Almond');
INSERT INTO ITEMS (ID,ITEM_NAME) VALUES (3,'Honey3');
INSERT INTO ITEMS (ID,ITEM_NAME) VALUES (4,'Almond4');
INSERT INTO ITEMS (ID,ITEM_NAME) VALUES (5,'Honey5');
INSERT INTO ITEMS (ID,ITEM_NAME) VALUES (6,'Almond6');
INSERT INTO ITEMS (ID,ITEM_NAME) VALUES (7,'Honey7');
INSERT INTO ITEMS (ID,ITEM_NAME) VALUES (8,'Almond8');